const productos = [
    {   "series": 1, 
        "id":"000",
        "name": "Batman Street of Gotham",
        "precio":"$39.990",
        "tipo":"DC",
        "comentario": "¡Dick Grayson y Damian Wayne son Batman y Robin, tendrán que pasarlo francamente mal para defender a los más vulnerables de Gotham, aunque lo intentarán por todos los medios y descubrirán oscuras facetas de la ciudad hasta un desenlace de órdago.!",
        "editorial":"DC Comics",
        "imagen":"https://i.postimg.cc/fy51qQfm/batman.jpg",
        "autor":"Paul Dini-Dustin Nguyen",
        "fecha":"23 de Noviembre del 2011",
        "paginas":"87",
        "tamaño":"16.8 x 25,8 cm",

        "formato":"Tapa dura",
    },
    {   "series": 1, 
        "id":"001",
        "name": "Batman Detective Comics",
        "precio":"$19.990",
        "tipo":"DC",
        "comentario": "Algo anda terriblemente mal con Batman. No importa las pruebas que Bruce realice, ni los números que cuente, el mejor detective del mundo no puede precisar la fuente de este temor creciente: sus propios demonios internos y una mortalidad inminente. Mientras tanto, demonios reales deambulan por las sombras mientras una antigua melodía acecha la noche de Gotham. Mientras Batman investiga las canciones y los demonios de Gotham, se ve obligado a enfrentar la pregunta más antigua: ¿Ha habido un demonio dentro de él todo este tiempo? Y si es así, ¿qué quiere... y por qué no ha asumido el control todavía?",
        "editorial":"DC Comics",
        "imagen":"https://i.postimg.cc/V68TYk7X/terror.jpg",
        "autor":"Paul Dini-Dustin Nguyen",
        "fecha":"19 de Septiembre del 2014",
        "paginas":"95",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {   "series": 2, 
        "id":"002",
        "name": "The Amazing Spider-Man Grim Hunt",
        "precio":"$39.990",
        "tipo":"marvel",
        "comentario": "Hace varios años, uno de los mayores enemigos de Spider-Man, Kraven el Cazador, acechó a su última presa y murió con un honor violento y mal concebido. Ahora, dos mujeres que dicen ser su esposa e hija han seguido a Spider-Man a través de la jungla urbana, debilitándolo a través del Guantelete mientras se preparan para intentar una resurrección impía. Están cazando arañas... y los amigos y tocayos de Spider-Man están en su punto de mira. J.M. DeMatteis, autor del clásico Kravens Last Hunt regresa a Amazing Spider-Man con Max Fiumara para explorar una confrontación desconocida entre Kraven y el violento doble de Spidey KAINE Coleccionando AMAZING SPIDER-MAN.",
        "editorial":"Marvel Comics",
        "imagen":"https://i.postimg.cc/TPmFMDcR/spiderman.jpg",
        "autor":"Michael Lark, Marc Guggenheim, Joe Kelly",
        "fecha":"28 de Noviembre del 2006 ",
        "paginas":"96",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {   "series": 2, 
        "id":"003",
        "name": "X-Men Wolverine Part II",
        "precio":"$14.990",
        "tipo":"marvel",
        "comentario": "Como consecuencia de X-MEN: SCHISM, los X-Men se dividen en dos. En el primer número sobredimensionado de la nueva serie insignia de los X, Wolverine se lleva a una mitad de los X-Men de vuelta a Westchester para empezar de nuevo. ¿Pero el nuevo Club Fuego Infernal sobrevivirá a su primer día? Únete al arquitecto de Marvel Jason Aaron (X-MEN: SCHISM, WOLVERINE) y al legendario artista X Chris Bachalo (AMAZING SPIDER-MAN, GENERATION X) para una nueva visión de los X-Men llena de acción que establecerá un nuevo estándar para los Hijos del Átomo.",
        "editorial":"Marvel Comics",
        "imagen":"https://i.postimg.cc/k4vHDPZz/wolverine.jpg",
        "autor":"Jason Aaron",
        "fecha":"26 de Octubre del 2011",
        "paginas":"157",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {   "series": 3, 
        "id":"004",
        "name": "Dragon ball Super saga Moro",
        "precio":"$9.990",
        "tipo":"manga",        
        "comentario": "Dragon Ball Super cuenta la historia que sigue al enfrentamiento contra Majin Boo. Goku y sus amigos deben enfrentarse a nuevos múltiples desafíos: desde un torneo contra representantes de otro universo hasta otro contra ¡todos los universos! Y también el regreso de Trunks del futuro y la amenaza de una versión malvada de Goku. Con personajes entrañables que hacen su reaparición y nuevos personajes como el dios de la destrucción, Beerus. ¡Más poderes! ¡Más transformaciones! Todo se eleva a la SÚPER potencia en este manga.",
        "editorial":"Jump Comics",
        "imagen":"https://i.postimg.cc/yYYMgW7P/goku.jpg",
        "autor":"Akira Toriyama",
        "fecha":"22 de Octumbre de 2021",
        "paginas":"35",
        "tamaño":"11,5 x 17,1 cm",
        "formato":"Tapa blanda",
    },
    {   "series": 3, 
        "id":"005",
        "name": "Jujutsu Kaisen Shibuya arc",
        "precio":"$19.990",
        "tipo":"manga",        
        "comentario": "Arco de El Incidente de Shibuya (渋谷事変 Shibuya Jihen?) es el nombre del noveno arco argumental de la serie manga Jujutsu Kaisen. A las 7:00 PM del 31 de octubre de 2018, aparece una extraña Pantalla cubriendo todo el Distrito de Shibuya, la cuál permite que los civiles y chamanes entren pero no puedan salir. Los habitantes encerrados dentro de la pantalla piden por la aparición de Satoru Gojo, ya que su aparición es la única condición que necesitan para salir.",
        "editorial":"Jump Comics",
        "imagen":"https://i.postimg.cc/t48wM5WS/kaisen.jpg",
        "autor":"Gege Akatsumi",
        "fecha":"15 de Noviembre del 2020",
        "paginas":"35",
        "tamaño":"11,5 x 17,1 cm",
        "formato":"Tapa blanda",
    },
    {   "series": 2, 
        "id":"006",
        "name": "The world Greatest comic Magazine Deadpool",
        "precio":"$18.990",
        "tipo":"marvel",        
        "comentario": "¡Los 90 están de regreso! Antes de que X-Force fuera X-Force (digamos, por New Mutants #98) , Cable conoció al mercenario bocón… ¡Y no fue nada agradable! Munición gruesa, viajes en el tiempo y cambios de continuidad, todo en esta historia que transcurre inmediatamente antes de que Deadpool hiciera su debut en el cómic, el 10 de febrero de 1991.",
        "editorial":"Marvel Comics",
        "imagen":"https://i.postimg.cc/c1mqLfGC/dead.jpg",
        "autor":"Swierczynski, Larraz, Woodard",
        "fecha":"4 de Marzo del 2009",
        "paginas":"87",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {   "series": 2, 
        "id":"007",
        "name": "The Invincible Iron Man",
        "precio":"$20.990",
        "tipo":"marvel",        
        "comentario": "Descripción Genio, multimillonario, playboy y... ¿loco? Tony Stark ha encontrado su contrapartida. Se llama Feilong. El industrial que odia a muerte a los mutantes es el nuevo dueño de Stark Ilimitado, lo que incluye toda la tecnología que desarrolló Tony. Adivina qué hará con ella...",
        "editorial":"Marvel Comics",
        "imagen":"https://i.postimg.cc/1XRjqY1t/iron.jpg",
        "autor":"Gerry Duggan, Juan Frigeri",
        "fecha":"24 de Febrero del 2004",
        "paginas":"98",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {   "series": 2, 
        "id":"008",
        "name": "El capitan america la Leyenda viviente",
        "precio":"$12.990",
        "tipo":"marvel",        
        "comentario": "Luego de que un satélite de investigaciones secretas es derribado en órbita por una fuerza desconocida, Steve Rogers, el ejército de un solo hombre, se convierte en lo único que podría detener una guerra entre dos superpotencias. Intrigas que datan de la Segunda Guerra Mundial y la Guerra Fría, y que pondrán a una leyenda viviente como el Capitán América en la cacería de otra leyenda… pero mucho más oscura.",
        "editorial":"Marvel Comics",
        "imagen": "https://i.postimg.cc/rFnvScmL/capitan.jpg",
        "autor":"Andy Diggle, Adi Granov, Agustin Alessio",
        "fecha":"8 de Julio del 2003",
        "paginas":"78",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {
        "series": 3, 
        "id": "009",
        "name": "Hunter X Hunter Primer manga",
        "precio": "$34.990",
        "tipo":"manga",
        "comentario":"Un mundo fantástico en el que existen bestias maléficas, tesoros ocultos… y hunters o “cazadores”, personas que viven increíbles peripecias para desentrañar los misterios del planeta. Gon no piensa detenerse hasta cumplir su verdadero objetivo: encontrar al legendario hunter Ging Freecss, ¡su padre, que desapareció cuando él era un niño!",
        "editorial": "Jump Comics",
        "imagen": "https://i.postimg.cc/7Z5j9cGJ/gon.jpg",
        "autor":"Yoshihiro Togashi",
        "fecha":"3 de Marzo del 1998",
        "paginas":"35",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa blanda",
    },
    {
        "series": 1, 
        "id": "010",
        "name": "CatWoman Faces of Evil",
        "precio": "$19.990",
        "tipo": "DC",
        "comentario": "Catwoman (traducido como Gatúbela en algunos países hispanohablantes) es el alias de Selina Kyle, una ladrona de guante blanco moralmente reformada, con una relación romántica de idas y venidas con Batman. Se muestra como una mujer tenaz, independiente, y muy conflictiva con su pasado.",
        "editorial": "DC Comics",
        "imagen": "https://i.postimg.cc/T2b5RStX/catwoman.jpg",
        "autor":"Paul dini, Dustin Nguyen",
        "fecha":"9 de Marzo del 2009",
        "paginas":"106",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {
        "series": 2, 
        "id": "011",
        "name": "The Avengers 60 Years",
        "precio": "$39.990",
        "tipo": "marvel",
        "comentario": "Los Vengadores fueron un equipo compuesto por personas extraordinarias, individuos alterados u otras características especiales, que se encargaba de proteger la Tierra de las amenazas internacionales o alienígenas.",
        "editorial": "Marvel Comics",
        "imagen": "https://i.postimg.cc/Dwx8jKw1/avengers.webp",
        "autor":"Andy Diggle, Adi Granov, Agustin Alessio",
        "fecha":"3 de Marzo del 2003",
        "paginas":"203",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {
        "series": 3, 
        "id": "012",
        "name": "My Hero Academia-Boku no Hero",
        "precio": "$19.990",
        "tipo": "manga",
        "comentario": "Se basa en un one-shot realizado por el mismo autor y publicado en el quinto volumen del manga Omagadoki DObutsuen bajo el nombre de My Hero. Una historia de héroes y villanos con superpoderes y sus enfrentamientos mientras tratas de dominar sus poderes. ¡No te pierdas esta magnífica serie de manga que te encantará!",
        "editorial": "Jump Comics",
        "imagen": "https://i.postimg.cc/kXFVSSr1/hero.jpg",
        "autor":"Kohei Horikoshi",
        "fecha":"20 de Septiembre del 2017",
        "paginas":"50",
        "tamaño":"11,5 x 17,1 cm",
        "formato":"Tapa blanda",
    },
    {
        "series": 1, 
        "id": "012",
        "name": "Batman Three Jokers",
        "precio": "$24.990",
        "tipo": "DC",
        "comentario": "Joker es uno de los personajes más emblemáticos de DC y uno de los iconos de la historia del cómic. Un villano sin pasado, el mal y el caos sin motivación ni explicación aparente, lo que lo convertía en un enemigo impredecible y sin debilidades sentimentales.",
        "editorial": "DC Comics",
        "imagen": "https://i.postimg.cc/fThtkKPS/joker.jpg",
        "autor":"Johns, Jason Gabok",
        "fecha":"14 de Mayo del 2018",
        "paginas":"107",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {
        "series": 1, 
        "id": "012",
        "name": "Flash Point",
        "precio": "$29.990",
        "tipo": "DC",
        "comentario": "Flash es el hombre más rápido vivo. El protector de Ciudad Central y Keystone, famoso por su súper-velocidad. Su legado, la Familia Flash se extiende a lo largo de la historia recurriendo a la enigmática Fuerza de Velocidad para ganar sus poderes.",
        "editorial": "DC Comics",
        "imagen": "https://i.postimg.cc/vT543g4m/flash.jpg",
        "autor":"Johns, Jason Gabok",
        "fecha":"18 de Abril del 2017",
        "paginas":"120",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {
        "series": 3, 
        "id": "012",
        "name": "Kimetsu No Yaiba Mugen Train",
        "precio": "$14.990",
        "tipo": "manga",
        "comentario": "La obra sigue las aventuras de Tanjirō Kamado, un adolescente cuya familia fue cruelmente asesinada por un Demonio el cual convirtió a su hermana Nezuko en una de estas criaturas, obligando a Tanjirō a emprender un viaje para cazar a estos seres y de paso ayudar a su hermana a recuperar su humanidad.",
        "imagen": "https://i.postimg.cc/FK11wnY8/kimetsu.jpg",
        "autor":"Koyoharu Gotouge",
        "fecha":"17 de Agosto del 2018",
        "paginas":"50",
        "tamaño":"11,5 x 17,1 cm",
        "formato":"Tapa blanda",
    },
    {
        "series": 1, 
        "id": "012",
        "name": "SuperMan",
        "precio": "$29.990",
        "tipo": "DC",
        "comentario": "Superman es uno de los seres más poderosos de DC Comics o incluso es considerado el más poderoso del Universo. Los poderes de Superman se deben a que sus células Kryptonianas absorben y almacenan la energía del sol amarillo de la Tierra, brindándole y aumentando sus habilidades asombrosas.",
        "editorial": "DC Comics",
        "imagen": "https://i.postimg.cc/y81DyNsV/superman.jpg",
        "autor":"Johns, Jason Gabok, Quintana, Mendoza",
        "fecha":"18 de Noviembre del 2007",
        "paginas":"178",
        "tamaño":"16.8 x 25,8 cm",
        "formato":"Tapa dura",
    },
    {
        "series": 3, 
        "id": "012",
        "name": "Shingeki no Kyojin",
        "precio": "$18.990",
        "tipo": "manga",
        "comentario": "La historia se desarrolla en un mundo ficticio en el que la humanidad está al borde de la extinción a causa de unas criaturas humanoides llamadas «titanes», lo que obliga a los supervivientes a refugiarse en tres enormes murallas que impiden el acceso a dichos monstruos.",
        "editorial": "Jump Comics",
        "imagen": "https://i.postimg.cc/KYV4brLz/titan.jpg",
        "autor":"Hajime Isayama",
        "fecha":"17 de Agosto del 2016",
        "paginas":"50",
        "tamaño":"11,5 x 17,1 cm",
        "formato":"Tapa blanda",
    },
    
];

module.exports = {
    productos
}